# Ubuntu base image
#
# VERSION 0.1.0

MAINTAINER Ian Truslove "ian.truslove@gmail.com"

# Start with Precise LTS
FROM iant/base:0.1.0

# Get base system's updates
RUN apt-get update
RUN apt-get upgrade -y