# Ubuntu base image
#
# VERSION 0.1.0

# Start with Precise LTS
FROM ubuntu:12.04

MAINTAINER Ian Truslove "ian.truslove@gmail.com"

# Get base system's updates
RUN apt-get update
RUN apt-get upgrade -y
